version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: naivecms
      POSTGRES_PASSWORD: naivecms
      POSTGRES_DB: naive
    ports:
      - "5432:5432"
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: naivecms
      MONGO_INITDB_ROOT_PASSWORD: naivecms
      MONGO_INITDB_DATABASE: naive
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
    driver: local
  mongodb_data:
    driver: local

